### ISSUE TITLE
Property/environment variables don't see to work. How to check venv is correctly set up?

### ISSUE THREAD

**Issue by hmf** [scalapy/scalapy#276]
The system variables "jna.library.path", "scalapy.python.library" and "scalapy.python.programname" don't seem to have any effect. ScalaPy seems to work no matter what I set. 

I am testing SacalPy using Scala 3. I use [Mill](https://github.com/com-lihaoyi/mill) as a build tool. I copied and pasted the code used in SBT from [installation section](https://scalapy.dev/docs/#installation). A quick test using [these code snippets](https://scalapy.dev/docs/#hello-world) works correctly. 

I then tried setting different values for (I set the last 2 of these in the object initializer that has the `main` function, see below):

* "jna.library.path"
* "scalapy.python.library"
* "scalapy.python.programname"  

Whether or not I set them incorrectly, the system still works. 8-) Here is an example: 

I use javaOption = -Djna.library.path=/usr/lib/python3.8/config-3.8-x86_64-linux-gnu
and I get `py.module("sys").executable = /usr/bin/python3`. This seems to be correct.

If I set `scalapy.python.programname = "/home/user/VSCodeProjects/rl-airegio/venv/bin/python"` I
get `py.module("sys").executable = /home/user/VSCodeProjects/rl-airegio/venv/bin/python`.  But if I change this to a non-existant binary, its still works.

Same happens when I set the python version to a non-existant version.

One thing that does seem to work is if I activate the virtual environment and run the Mill script
then I get `py.module("sys").executable = /home/user/VSCodeProjects/rl-airegio/venv/bin/python`
as expected without setting anything.

So what is the best way to check that I am pointing to the correct environment? Save for the virtual 
environment, when/why do I need to set these variables? It seems like I can set two of these to incompatible versions, then shouldn't it fail? 

TIA

```scala
object FFIPythonHello:


  // No effect
  val pythonVersionProperty = "scalapy.python.library"

  // No effect
  val venvPythonProperty = "scalapy.python.programname"

  val venvPython = "/home/user/VSCodeProjects/rl-airegio/venv/bin/python"
  val pythonVersion = "python3.18"

  //System.setProperty(venvPythonProperty, venvPython)
  //System.setProperty(pythonVersionProperty, pythonVersion)
    

  def main(args: Array[String]): Unit =

    println("FFIPython")

    val exec = py.module("sys").executable 
    println(s"exec = $exec")

    // https://docs.python.org/3/library/sys.html
    val platform = py.module("sys").platform
    println(s"platform = $platform")

    // https://docs.python.org/3/library/sys.html (only in 3.9)
    //val lib = py.module("sys").platlibdir

    val listLengthPython = py.Dynamic.global.len(List(1, 2, 3).toPythonProxy)
    // listLengthPython: py.Dynamic = 3
    println(s"listLengthPython = $listLengthPython")

    val listLength = listLengthPython.as[Int]
    // listLength: Int = 3    
    println(s"listLength = $listLength")


end FFIPythonHello
```

**Comment by kiendang** [comment]
In the current release version of ScalaPy, if the `scalapy.python.library` you manually set is invalid ScalaPy will try some generic option e.g. `python`, `python3`, `python3.7`, ... This has been disabled in a recent PR #270.

You seemed to ask about `scalapy.python.programme` though. That option is passed into the Python C API function [`Py_SetProgramName`](Py_SetProgramName) during initialization. Python then use it to set the executable path. My guess is if it's invalid, Python will just disregard it and use the default one?

> One thing that does seem to work is if I activate the virtual environment and run the Mill script
then I get py.module("sys").executable = /home/user/VSCodeProjects/rl-airegio/venv/bin/python
as expected without setting anything.

If you don't set any option then ScalaPy will just use `python` in the current environment. So it makes sense that if you activate your venv then it would just work.

**Comment by hmf** [comment]
@kiendang Thanks for the feedback. I think #270 is a good option.
