### ISSUE TITLE
sbt-scalapy plugin

### ISSUE THREAD

**Issue by kiendang** [scalapy/scalapy#280]
Last week I worked on a sbt plugin for automatic ScalaPy setup at [kiendang/sbt-scalapy](https://github.com/kiendang/sbt-scalapy). Let me know what you think. If it looks ok I'll move it into the org and start publishing artifacts then work on the docs. Usage details is in the readme. A minimal build looks like this

In `project/plugins.sbt`

```scala
addSbtPlugin("ai.kien" % "sbt-scalapy" % "<version>")

// use this instead for scala native
// addSbtPlugin("ai.kien" % "sbt-scalapy-native" % "<version>")
```

In `build.sbt`

```scala
enablePlugins(ScalaPyPlugin)
// set the Python you want to use otherwise use the default one in the current environment
// scalapyPythonExecutable := "..."
```

**Comment by shadaj** [comment]
This looks amazing! We should definitely move it into the org.

One piece of feedback, we should see if we can combine the JVM / Scala Native plugins under a single package to further simplify the setup. SBT autoplugins should make it possible to selectively enable different sub-plugins depending on whether Scala Native is available.

**Comment by shadaj** [comment]
Also opened #282, once that's done I can help get publishing set up.

**Comment by kiendang** [comment]
> One piece of feedback, we should see if we can combine the JVM / Scala Native plugins under a single package to further simplify the setup. SBT autoplugins should make it possible to selectively enable different sub-plugins depending on whether Scala Native is available.

This would be a very simple thing to change. I was considering between the 2 approaches and chose the current one so that JVM project doesn't need to pull scala native related code, kind of like `sbt-crossproject` (scalajs only project doesn't need to pull scala native related code and vice versa). But you're right, the amount of code is tiny anyway and it's not worth the extra complexity.

> Also opened #282, once that's done I can help get publishing set up.

Great! I was thinking about this too. Will move it into the org first then publish artifacts when #282 is done.

**Comment by kiendang** [comment]
This is now done kiendang/sbt-scalapy#8.
