### ISSUE TITLE
Issues calling scipy.linalg.solve on large matrices on macOS

### ISSUE THREAD

**Issue by sfriedowitz** [scalapy/scalapy#283]
Hello,

I've been attempting to use `sklearn` through Scalapy within my Scala project, and have run into an issue where the Scala process finishes with the error `Process finished with exit code 132 (interrupted by signal 4: SIGILL)`. I was able to narrow it down, and this error is specifically occurring when the `sklearn` code calls `scipy.linalg.solve`, and only in cases where the matrix/vectors have > 100 dimensions. My hunch is that this is related to the inner LAPACK routines being called within `scipy.linalg.solve`, and some internal check on the argument dimensionality.

After googling around a bit, I found that this general error is related to an illegal instruction set provided to the processor, and has commonly popped up on the new Mac w/ M1 chips. I am running on a Macbook, but with an older Intel chip, so it can't be related to the M1 chips. I also do not have issues running this Python code in the same environment outside of Scalapy, which implies to me that the issue lies in how Scalapy is accessing the Python environment.

I am wondering if you have had any similar issues when calling Python code that wraps native routines, and if there are any known workarounds for this type of issue?

**Comment by shadaj** [comment]
Interesting, how have you installed `sklearn`? I wonder if ScalaPy is using a different Python installation than the one you used to test manually. Another thing to check is how you are passing in data; to make sure the data is available just like `sklearn` expects it, you should use `toPythonCopy` rather than `toPythonProxy`.

**Comment by sfriedowitz** [comment]
Yep! `sklearn` is installed in this environment. I think Scalapy is using the correct environment since `sklearn` and `scipy` are not installed in my base conda environment, so I would expect a ModuleImportError if I was mistakenly running off base. 

In fact, the code I was running that uses sklearn in Scalapy works fine....up to a matrix/vector dimensionality of 100. So something very baffling is going on here. I wonder if you can reproduce? Specifically, I was in a python3.9 environment with the only installed requirements of numpy==1.22.0 and sklearn==1.0.2.

And yes, I am passing the data using `toPythonCopy` in this instance.

**Comment by sfriedowitz** [comment]
Sorry, misread your first question. `sklearn` was installed by a pip install in a specific conda environment.

**Comment by shadaj** [comment]
Looking at https://github.com/ninia/jep/issues/241, it seems that a fix may be to set a larger stack size on the JVM?

**Comment by sfriedowitz** [comment]
Wow! Impressive tracking that down @shadaj . I'll give it a shot in the coming days and report back.

**Comment by sfriedowitz** [comment]
@shadaj Verified that the fix you linked solves my issue. Setting the JVM stack size `-Xss4m` allows the previously failing code to run.
