### ISSUE TITLE
Calling the Python 'print' method prints nothing when the output isn't a terminal

### ISSUE THREAD

**Issue by alexarchambault** [scalapy/scalapy#309]
Illustrating this with the latest Scala CLI ([`0.1.14`](https://github.com/VirtusLab/scala-cli/releases/tag/v0.1.14)), whose `run` sub-command accepts a `--python` option that sets things up using [python-native-libs](https://github.com/scalapy/python-native-libs):
```text
$ scala-cli run -S 2.13 --python <(echo 'py.Dynamic.global.print("Hello")') | cat
$ scala-cli run -S 2.13 --python <(echo 'py.Dynamic.global.print("Hello")')
Hello
```

This is happening to me on macOS, I didn't try on Linux yet.

**Comment by alexarchambault** [comment]
Although I reproduced that here using Scala CLI, this is also happening to me outside of it, when running things from standard JARs.

**Comment by alexarchambault** [comment]
Same thing from Scala Native too.

**Comment by alexarchambault** [comment]
Thanks a lot for the workaround, @kiendang!

Don't know if this issue should be closed… It seems `python` binary ensures its stdout is flushed. Maybe ScalaPy could do the same somehow (not sure what that requires…).

**Comment by kiendang** [comment]
You also need `python -u` to force the stdout and stderr streams to be unbuffered. In this case (`python <(echo 'print("Hello")') | cat`) and in general printing without `-u` or `PYTHONUNBUFFERED` usually works fine but in some cases it doesn't, *e.g.* inside containers, and the solution is usually just setting `PYTHONUNBUFFERED=1` and move on. I do agree that this case is interesting though and maybe worth looking into.
