### ISSUE TITLE
Confusing error message when creating trait facades in Scala 3

### ISSUE THREAD

**Issue by cric96** [scalapy/scalapy#310]
## Problem
If you try to create a static facade as the one shown in the example [here](https://scalapy.dev/docs/static-types#defining-type-facades), the compiler produces the following error:
https://pastebin.pl/view/5627d827
## How to reproduce
[here](https://scastie.scala-lang.org/Qcgk5wtaRqisXS5GdTXVrw) there is a Scastie playground that shows the problem
## Workaround
It seems that using `class` instead of `trait` remove the compiler error. (in scala 2.* the trait solution works without any problem).

**Comment by shadaj** [comment]
We have a note in the docs "Note: If using Scala 3, you should define a static type as a subclass, instead of a trait as shown in this example." that is meant to clarify this difference. We should probably generate a better compiler warning than a crash though.

**Comment by shadaj** [comment]
Fixed by #312
