### ISSUE TITLE
How to call Python method and get String?

### ISSUE THREAD

**Issue by hmf** [scalapy/scalapy#311]
I am trying to instantiate an object in Python, access it in Scala and call a method there that returns a `String`. I have tried several ways but keep getting this error:

```shell
me.shadaj.scalapy.py.PythonException: <class 'TypeError'> bad argument type for built-in operation
```

Please note that I am using Scala 3 and the [this example](https://scalapy.dev/docs/static-types#defining-type-facades) works fine (when I change trait to class). 

Here are the facades I have:

```scala
package py

import me.shadaj.scalapy.py

@py.native class PyString extends py.Object {
  def count(subsequence: String): Int = py.native
}

// @py.native class PyState extends py.Object {
@py.native class PyState extends py.Any {
  // val i: String = py.native
  def f(): PyString = py.native
}
```
 Her is my Python:

```Python

class State:
    """A simple example class"""
    i = 12345

    def f(self):
        return 'hello world'

def new_state():
    return State()
```

And here is my Scala client:

```Scala
    val sim = py.module("sim")
    val stateT = sim.new_state()
    println(stateT)
    val state = stateT.as[ppy.PyState]
    val stateF = state.f()
    println(stateF)
    println(stateF.as[String])
```
which prints:

```shell
<sim.State object at 0x7fce442bc6a0>
<bound method State.f of <sim.State object at 0x7fce442bc6a0>>
```

The line `println(stateF.as[String])` is causing the exception. Originally I had no `PyString` and returned a String directly. But I got the same `TypeError`. I also tried a `val` in the facade but that failed with another error. 

Can anyone tell me what I am doing wrong?

TIA

**Comment by shadaj** [comment]
This looks like a bug with how we handle facades in Scala 3, it seems that the the definition `def f()` is being treated the same as `def f` (we don't support defining facades as `val`/`var`), even though the former should correspond to calling `f()`.

I see two paths from here: either we distinguish empty-parens functions from functions without any parentheses (as in Scala 2), or make all facade methods correspond to a function call and introduce a new annotation to mark methods that are facades for attributes. I'm currently leaning towards the latter, but this would be a fairly large breaking change.

**Comment by hmf** [comment]
@shadaj Thanks for taking the time to look at this. Thanks also for developing this project.

> the definition def f() is being treated the same as def f (we don't support defining facades as val/var), even though the former should correspond to calling f().

Scala 3 differentiates between these two cases (no conversion between the 2). Here is a [scastie example](https://scastie.scala-lang.org/bF3ZQrnLRjykCot81OLgqA). However, it does seem that a `val` might be treated as a `def` with no parenthesis. Maybe `vals` can also be supported? 

> I see two paths from here: either we distinguish empty-parens functions from functions without any parentheses (as in Scala 2), 

Personally I think your first solution is better because it is simpler from the client's perspective.  It also seems to be more in line with Scala 3'd compiler behavior. 

As for anyone that has this issue, as a hack, one can declare the function to take in a dummy parameter with a  default such as:

```scala
@py.native class PyState extends py.Any {
  def p(s:Int = -1): String = py.native
}
```

And this "works":

```scala
    val sim = py.module("sim")
    val stateT = sim.new_state()
    val stateG = state.p(0)
    println(s"stateG(0) = $stateG")
    val stateG2 = state.p()
    println(s"stateG2(0) = $stateG2")
```
