### ISSUE TITLE
Is it possible to create a fat jar?

### ISSUE THREAD

**Issue by lkyhfx** [scalapy/scalapy#354]
The document only provide example for running the code using `sbt run`, is it possible to create a fat jar?

**Comment by kiendang** [comment]
If you mean a fat jar with python dependencies then no. Otherwise I don't see why https://github.com/sbt/sbt-assembly wouldn't work.

**Comment by lkyhfx** [comment]
So, how to use scalapy in production if can't produce a jar which can be deployed on a server? Is using docker the only option?

**Comment by lkyhfx** [comment]
> You can produce a fat jar for your JVM deps, but you'll still need to install the Python env on your production machine in some way (Pip/Conda/Poetry...).
> 
> There might be ways to pre-create that env, pack it, and extract it on the target machine but without something like Docker to automate it will take some effort and is a portability minefield.

After producing a fat jar using the assembly plugin and running it with `java -jar -Dscalapy.python.programname=/usr/bin/python xxxx-assembly.jar`, I encountered this error
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to load library 'python3':
libpython3.so: cannot open shared object file: No such file or directory
libpython3.so: cannot open shared object file: No such file or directory
Native library (linux-x86-64/libpython3.so) not found in resource path (target/scala-2.13/scalapy-assembly-0.1.0-SNAPSHOT.jar)
```

**Comment by kiendang** [comment]
@lkyhfx I see. Instead of setting up scalapy in sbt, you can do it in your main method instead, i.e. adding `python-native-libs` to your project dependencies then add this to your main method

```scala
def main(args: Array[String]): Unit = {
  ai.kien.python.Python("</path/to/python>").scalapyProperties.fold(
    ex => println(s"Error while getting ScalaPy properties: $ex"),
    props => props.foreach { case(k, v) => System.setProperty(k, v) }
  )
  ...
}
```

**Comment by lkyhfx** [comment]
@kiendang Thanks! I have already figured out a better solution. I'm leaving it here for anyone who has the same need:

Here are the steps to follow:
1. Refer to the ScalaPy documentation and follow the instructions until you can successfully run the program using `sbt run`.
2. To build a fat jar, utilize the assembly plugin.
3. You can now run the fat jar using the following command: `java -Djna.library.path=xxx -Dscalapy.python.library=xxx -Dscalapy.python.programname=xxx -jar xxx.jar`. These three JVM options are necessary for Java to locate the Python library. If you're unsure about assigning these options, you can open an SBT shell within the project and execute `show javaOptions`. If your configuration is correct in `build.sbt`, the command should output the correct parameters for you.
4. Finally, you can distribute this fat jar and run it on any environment with the same Python setup. It is recommended to use a Python virtual environment, as it will make replicating the same Python environment elsewhere easier.
