### ISSUE TITLE
Status of scalapy project

### ISSUE THREAD

**Issue by adriaant** [scalapy/scalapy#355]
Seeing that the latest version is from november last year and there are quite a few unmerged PRs, I was wondering if this project is still actively maintained? If not, how can we help?

**Comment by shadaj** [comment]
Hi! Unfortunately, I've not had much time to work on new features for ScalaPy in recent months (my day job / research involves a lot more Rust). I'm happy to review any PRs, though, just don't have the bandwidth to work on new features myself.

**Comment by vishalovercome** [comment]
Perhaps pin this issue for folks who might be interested in learning more about it?

**Comment by daenenk** [comment]
I tried to see how far I got on branch `maintenance/update-scala-versions`, but didn't get far. See my comments on #381 .
