### ISSUE TITLE
What is the status and roadmap of this project?

### ISSUE THREAD

**Issue by vishalovercome** [scalapy/scalapy#365]
Hello! This project has a lot of potential. However, it seems as though it hasn't been maintained since last year. Can @shadaj / @kiendang or anyone else please clarify whether the plans for this project are?

**Comment by kiendang** [comment]
@vishalovercome see Shadaj's comment here https://github.com/scalapy/scalapy/issues/355#issuecomment-1661525278

**Comment by vishalovercome** [comment]
Thanks! That helps. Perhaps pin that issue for folks who might be interested in learning more about it?
