### ISSUE TITLE
Artifacts for Scala native 0.5 are missing

### ISSUE THREAD

**Issue by daenenk** [scalapy/scalapy#382]
No artifacts have been published yet in https://repo1.maven.org/maven2/dev/scalapy/scalapy-core_native0.5_3/

I tried using
```
libraryDependencies += "dev.scalapy" %%% "scalapy-core" % "0.5.3"
```

in a project with
```
scalaVersion := "3.4.1"
```

and in plugins.sbt
```
addSbtPlugin("org.scala-native" % "sbt-scala-native" % "0.5.0")
```

I hope to see support for scala-native 0.5.x coming soon.
Thank you.

**Comment by kiendang** [comment]
Looks like there's an open PR #381 addressing this. Note that this lib is not in active development (see https://github.com/scalapy/scalapy/issues/355#issuecomment-1661525278) so this might take a bit.
